export const INVOKE_CHANNELS = new Set([
  'auth:open-webview', 'auth:exchange-code', 'auth:get-profile', 'auth:get-tokens', 'auth:refresh', 'auth:status', 'auth:logout', 'auth:update-profile', 'auth:is-online',
  'filesystem:read-file', 'filesystem:write-file', 'filesystem:list-dir', 'filesystem:delete-file',
  'dialog:open-file', 'dialog:save-file', 'clipboard:read-text',
  'notifications:list', 'notifications:dismiss', 'notifications:mark-read',
  'settings:get', 'settings:set', 'settings:get-all', 'settings:reset',
  'sync:status', 'sync:trigger',
  'workspace:list', 'workspace:get', 'workspace:create', 'workspace:update', 'workspace:delete', 'workspace:stats',
  'entity:list', 'entity:get', 'entity:create', 'entity:update', 'entity:delete',
  'entity:restore', 'entity:archive', 'entity:duplicate', 'entity:children', 'entity:create-child',
  'entity-types:list', 'entity-types:create',
  'entity-properties:list', 'entity-properties:create',
  'block:list', 'block:get', 'block:entity-blocks', 'block:delete',
  'relation:list', 'relation:get', 'relation:create', 'relation:delete',
  'relation:outgoing', 'relation:backlinks', 'relation:neighbors', 'relation:path',
  'tag:list', 'tag:get', 'tag:create', 'tag:update', 'tag:delete', 'tag:attach', 'tag:detach',
  'comment:list', 'comment:get', 'comment:create', 'comment:update', 'comment:delete',
  'file:list', 'file:get', 'file:upload', 'file:download', 'file:delete', 'file:link', 'file:unlink', 'file:cleanup-orphans',
  'backup:export', 'backup:import', 'backup:list', 'backup:auto-backup', 'backup:start-timer', 'backup:stop-timer',
  'backup:export-encrypted', 'backup:import-encrypted', 'backup:change-password',
  'backup:export-markdown', 'backup:export-zip', 'backup:export-html', 'backup:export-pdf',
  'backup:delete', 'backup:export-to-disk', 'backup:rotate-key',
  'graph:query', 'graph:materialize', 'graph:traverse', 'graph:paths',
  'search:keyword', 'search:semantic', 'search:hybrid',
  'ai:query', 'ai:suggest-relations', 'ai:summarize',
  'editor:block-create', 'editor:block-update', 'editor:block-move', 'editor:reorder',
  'versioning:history', 'versioning:snapshot', 'versioning:branches',
  'versioning:create-branch', 'versioning:diff', 'versioning:merge', 'versioning:resolve-conflict',
  'governance:health', 'governance:duplicates', 'governance:orphans', 'governance:stale',
  'activity:list', 'dashboard:overview', 'version:info', 'app:get-log-dir', 'app:export-logs',
])

export const SEND_CHANNELS = new Set([
  'window:minimize', 'window:maximize', 'window:close', 'window:set-title',
  'clipboard:write-text',
  'notifications:show',
])

export const RECEIVE_CHANNELS = new Set([
  'auth:status-changed', 'auth:code-received',
  'file:import-requested',
  'sync:status-changed',
  'search:open', 'search:open-replace',
  'editor:new-entity', 'editor:save',
  'update:checking', 'update:available', 'update:not-available', 'update:progress', 'update:downloaded', 'update:error',
  'navigate:settings', 'navigate:graph', 'navigate:shortcuts', 'navigate:about',
  'view:toggle-sidebar', 'view:toggle-ai',
  'app:before-quit', 'app:quit-ready',
  'workspace:restore-last', 'workspace:create',
  'power:state-changed',
  'backup:export-dialog', 'backup:import-dialog',
  'renderer:error',
  'dialog:open-file',
  'server:start-failed',
])
